label: 'TinyInfoService'
port: 1234
refresh_interval_in_seconds: 2.0
infos:
  localhost:
    kind: shell_cmd
    shell_cmd: "uptime"
    transform: ".split('up').last.split('users').first.split(',').first(2).join.strip"
    cache: 1.5m
